version: "2"
services:
   jupyterlab:
      image: brunocu/hadoop
      container_name: jupyterlab
      command: "pyspark" 
      environment:
        PYSPARK_DRIVER_PYTHON_OPTS: "lab --notebook-dir=/var/jupyter/ --ip='*' --no-browser"
      ports:
        - 8888:8888
      env_file:
        - ./hadoop.env
   namenode:
      image: brunocu/hadoop
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 4040:4040
      env_file:
        - ./hadoop.env
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: brunocu/hadoop
      container_name: datanode
      command: ["hdfs", "datanode"]
      env_file:
        - ./hadoop.env      
   resourcemanager:
      image: brunocu/hadoop
      hostname: resourcemanager
      container_name: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./hadoop.env
   nodemanager:
      image: brunocu/hadoop
      container_name: nodemanager
      command: ["yarn", "nodemanager"]
      env_file:
        - ./hadoop.env
